const express = require('express');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const Database = require('better-sqlite3');

const app = express();
const PORT = Number(process.env.PORT || 3000);
// Vercel's deployed application directory is read-only. Keep local data beside
// the app, but use its writable temporary directory when running as a function.
// DATABASE_PATH can point at a writable persistent volume in other environments.
const dbPath = process.env.DATABASE_PATH || path.join(process.env.VERCEL ? '/tmp' : __dirname, 'club.db');
fs.mkdirSync(path.dirname(dbPath), { recursive: true });
const db = new Database(dbPath);
db.pragma('journal_mode = WAL');
db.pragma('foreign_keys = ON');
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

const today = () => new Date().toISOString().slice(0,10);
const num = v => Number(v || 0);
const legacyHash = s => crypto.createHash('sha256').update(String(s)).digest('hex');
const hashPassword = password => {
 const salt=crypto.randomBytes(16).toString('hex');
 return `scrypt$${salt}$${crypto.scryptSync(String(password),salt,64).toString('hex')}`;
};
const verifyPassword = (password, stored) => {
 if(!stored?.startsWith('scrypt$')) return legacyHash(password)===stored;
 const [,salt,digest]=stored.split('$');
 const actual=crypto.scryptSync(String(password),salt,64);
 return crypto.timingSafeEqual(actual,Buffer.from(digest,'hex'));
};
const validDate = value => /^\d{4}-\d{2}-\d{2}$/.test(String(value||''));
const cleanText = (value,max=500) => String(value||'').trim().slice(0,max);

function addColumn(table, col, type, def='') {
  const exists = db.prepare(`PRAGMA table_info(${table})`).all().some(x => x.name === col);
  if (!exists) db.exec(`ALTER TABLE ${table} ADD COLUMN ${col} ${type} ${def}`);
}

function audit(action, entity, entityId, details='', user='system') {
  db.prepare(`INSERT INTO audit_log(action,entity,entity_id,details,user_name,created_at) VALUES(?,?,?,?,?,datetime('now'))`).run(action, entity, entityId || null, details, user);
}

function init(){
 db.exec(`
 CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL);
 CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,category_id INTEGER,unit TEXT DEFAULT 'pcs',buy_price REAL DEFAULT 0,sell_price REAL DEFAULT 0,stock REAL DEFAULT 0,reorder_level REAL DEFAULT 0,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(category_id) REFERENCES categories(id));
 CREATE TABLE IF NOT EXISTS sales(id INTEGER PRIMARY KEY AUTOINCREMENT,sale_date TEXT NOT NULL,total REAL DEFAULT 0,payment_method TEXT DEFAULT 'Cash',note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS sale_items(id INTEGER PRIMARY KEY AUTOINCREMENT,sale_id INTEGER,product_id INTEGER,qty REAL,unit_price REAL,line_total REAL,FOREIGN KEY(sale_id) REFERENCES sales(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id));
 CREATE TABLE IF NOT EXISTS stock_moves(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER,move_type TEXT,qty REAL,unit_cost REAL DEFAULT 0,reference TEXT,note TEXT,move_date TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(product_id) REFERENCES products(id));
 CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,expense_date TEXT NOT NULL,category TEXT NOT NULL,amount REAL NOT NULL,description TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);
 CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
 CREATE TABLE IF NOT EXISTS price_history(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER,price_type TEXT NOT NULL,price REAL NOT NULL,effective_date TEXT NOT NULL,estimated INTEGER DEFAULT 0,source_note TEXT,FOREIGN KEY(product_id) REFERENCES products(id));
 CREATE TABLE IF NOT EXISTS purchases(id INTEGER PRIMARY KEY AUTOINCREMENT,supplier TEXT,invoice_no TEXT,purchase_date TEXT NOT NULL,total REAL DEFAULT 0,note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS purchase_items(id INTEGER PRIMARY KEY AUTOINCREMENT,purchase_id INTEGER,product_id INTEGER,qty REAL,buy_price REAL,line_total REAL,estimated INTEGER DEFAULT 0,FOREIGN KEY(purchase_id) REFERENCES purchases(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id));
 CREATE TABLE IF NOT EXISTS daily_closings(id INTEGER PRIMARY KEY AUTOINCREMENT,close_date TEXT UNIQUE NOT NULL,opening_cash REAL DEFAULT 0,cash_sales REAL DEFAULT 0,mpesa_sales REAL DEFAULT 0,card_sales REAL DEFAULT 0,other_sales REAL DEFAULT 0,expenses REAL DEFAULT 0,expected_cash REAL DEFAULT 0,actual_cash REAL DEFAULT 0,difference REAL DEFAULT 0,closed_at TEXT,closed_by TEXT,note TEXT);
 CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,action TEXT,entity TEXT,entity_id INTEGER,details TEXT,user_name TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 `);
 // Compatibility migrations for earlier versions.
 addColumn('products','price_estimated_buy','INTEGER','DEFAULT 0');
 addColumn('products','price_estimated_sell','INTEGER','DEFAULT 0');
 addColumn('products','source_note','TEXT','DEFAULT \'\'');
 addColumn('stock_moves','purchase_id','INTEGER','');
 addColumn('sales','voided_at','TEXT','');
 addColumn('sales','voided_by','TEXT','');
 addColumn('sales','void_reason','TEXT','');
 addColumn('sales','location_id','INTEGER','');
 addColumn('purchases','location_id','INTEGER','');
 addColumn('expenses','location_id','INTEGER','');
 addColumn('stock_moves','location_id','INTEGER','');
 db.exec(`
 CREATE TABLE IF NOT EXISTS locations(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,type TEXT NOT NULL DEFAULT 'OUTLET',active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS location_stock(id INTEGER PRIMARY KEY AUTOINCREMENT,location_id INTEGER NOT NULL,product_id INTEGER NOT NULL,quantity REAL DEFAULT 0,reorder_level REAL,UNIQUE(location_id,product_id),FOREIGN KEY(location_id) REFERENCES locations(id),FOREIGN KEY(product_id) REFERENCES products(id));
 CREATE TABLE IF NOT EXISTS stock_transfers(id INTEGER PRIMARY KEY AUTOINCREMENT,from_location_id INTEGER NOT NULL,to_location_id INTEGER NOT NULL,transfer_date TEXT NOT NULL,created_by TEXT,note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(from_location_id) REFERENCES locations(id),FOREIGN KEY(to_location_id) REFERENCES locations(id));
 CREATE TABLE IF NOT EXISTS stock_transfer_items(id INTEGER PRIMARY KEY AUTOINCREMENT,transfer_id INTEGER NOT NULL,product_id INTEGER NOT NULL,quantity REAL NOT NULL,FOREIGN KEY(transfer_id) REFERENCES stock_transfers(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id));
 CREATE TABLE IF NOT EXISTS location_closings(id INTEGER PRIMARY KEY AUTOINCREMENT,location_id INTEGER NOT NULL,close_date TEXT NOT NULL,opening_cash REAL DEFAULT 0,cash_sales REAL DEFAULT 0,mpesa_sales REAL DEFAULT 0,card_sales REAL DEFAULT 0,other_sales REAL DEFAULT 0,expenses REAL DEFAULT 0,expected_cash REAL DEFAULT 0,actual_cash REAL DEFAULT 0,difference REAL DEFAULT 0,closed_at TEXT,closed_by TEXT,note TEXT,UNIQUE(location_id,close_date),FOREIGN KEY(location_id) REFERENCES locations(id));
 CREATE TABLE IF NOT EXISTS rooms(id INTEGER PRIMARY KEY AUTOINCREMENT,room_name TEXT UNIQUE NOT NULL,room_type TEXT,price_per_night REAL DEFAULT 0,status TEXT DEFAULT 'Available',active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS guests(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS bookings(id INTEGER PRIMARY KEY AUTOINCREMENT,guest_id INTEGER NOT NULL,room_id INTEGER NOT NULL,check_in TEXT NOT NULL,check_out TEXT NOT NULL,nights INTEGER DEFAULT 1,rate REAL DEFAULT 0,total REAL DEFAULT 0,status TEXT DEFAULT 'Reserved',payment_status TEXT DEFAULT 'Unpaid',payment_method TEXT,note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(guest_id) REFERENCES guests(id),FOREIGN KEY(room_id) REFERENCES rooms(id));
 CREATE TABLE IF NOT EXISTS accommodation_payments(id INTEGER PRIMARY KEY AUTOINCREMENT,booking_id INTEGER NOT NULL,amount REAL NOT NULL,payment_date TEXT NOT NULL,payment_method TEXT,reference TEXT,received_by TEXT,FOREIGN KEY(booking_id) REFERENCES bookings(id));
 CREATE TABLE IF NOT EXISTS accommodation_expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,expense_date TEXT NOT NULL,category TEXT NOT NULL,amount REAL NOT NULL,description TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 `);
 const addLocation=db.prepare('INSERT OR IGNORE INTO locations(name,type) VALUES(?,?)');
 [['Big Club','OUTLET'],['Small Club','OUTLET'],['Store','STORE']].forEach(x=>addLocation.run(...x));
 const bigClub=db.prepare("SELECT id FROM locations WHERE name='Big Club'").get().id;
 // Preserve the legacy global product stock as the opening balance of Big Club exactly once.
 const migrated=db.prepare("SELECT 1 FROM settings WHERE key='location_stock_migrated'").get();
 if(!migrated){const put=db.prepare('INSERT OR IGNORE INTO location_stock(location_id,product_id,quantity,reorder_level) VALUES(?,?,?,?)'); for(const p of db.prepare('SELECT id,stock,reorder_level FROM products').all()) put.run(bigClub,p.id,p.stock,p.reorder_level); db.prepare('INSERT INTO settings(key,value) VALUES(?,?)').run('location_stock_migrated',today());}
 // Historical records belonged to the original Big Club operation.
 for(const table of ['sales','purchases','expenses','stock_moves']) db.prepare(`UPDATE ${table} SET location_id=? WHERE location_id IS NULL`).run(bigClub);

 const cats=['Beer','Spirits','Soft Drinks','Water','Food','Cans','Other'];
 const addCat=db.prepare('INSERT OR IGNORE INTO categories(name) VALUES(?)'); cats.forEach(name=>addCat.run(name));
 if(!db.prepare('SELECT 1 FROM users LIMIT 1').get()) db.prepare('INSERT INTO users(username,password_hash,role) VALUES(?,?,?)').run('admin',hashPassword('admin123'),'Administrator/Owner');
 if(!db.prepare('SELECT 1 FROM settings WHERE key=?').get('business_name')) db.prepare('INSERT INTO settings(key,value) VALUES(?,?)').run('business_name','Park Bar & Accommodation');
 seedProducts();
}

function seedProducts(){
 const existing = db.prepare('SELECT COUNT(*) n FROM products').get().n;
 if(existing > 0) return;
 const cats=Object.fromEntries(db.prepare('SELECT id,name FROM categories').all().map(x=>[x.name,x.id]));
 const rows = [
  // Beers
  ['Guinness','Beer','bottle',205,280,60,5],['Guinness Smooth','Beer','bottle',131,320,0,5],['Whitecap','Beer','bottle',196,280,75,5],['Tusker Cider','Beer','bottle',262,280,120,6],['Tusker Lager','Beer','bottle',169,250,100,12],['Tusker Lite','Beer','bottle',187,280,0,5],['Balozi','Beer','bottle',169,280,10,5],['Pineapple Punch','Beer','bottle',159,250,0,6],['Black Ice','Beer','bottle',159,250,0,5],['King Fisher','Beer','bottle',200,300,0,5],['K.O','Beer','bottle',200,300,0,5],['Hunter Gold','Beer','bottle',220,300,0,5],['Savannah','Beer','bottle',240,350,0,5],
  // Spirits / wines visible in sheets
  ['750ml Bond 7','Spirits','bottle',1400,2100,3,2],['350ml Bond 7','Spirits','bottle',750,1200,2,2],['250ml Bond 7','Spirits','bottle',550,900,3,2],['750ml Chrome','Spirits','bottle',883,1000,1,2],['250ml Chrome','Spirits','bottle',217,300,10,2],['750ml Gilbeys','Spirits','bottle',1500,2300,1,2],['350ml Gilbeys','Spirits','bottle',850,1300,3,2],['250ml Gilbeys','Spirits','bottle',600,900,3,2],['750ml Konyagi','Spirits','bottle',900,1200,0,2],['250ml Konyagi','Spirits','bottle',350,450,0,2],['750ml Kane Extra','Spirits','bottle',500,600,0,2],['250ml Kane Extra','Spirits','bottle',300,400,10,2],['750ml K.C','Spirits','bottle',1700,2500,11,2],['350ml K.C','Spirits','bottle',900,1400,0,2],['250ml K.C','Spirits','bottle',650,1000,18,3],['250ml Liberty','Spirits','bottle',600,950,2,2],['750ml General Meakins','Spirits','bottle',1400,2100,1,2],['250ml General Meakins','Spirits','bottle',600,900,2,2],['750ml Fourthstreet','Spirits','bottle',1500,2300,2,2],['750ml Four Cousins','Spirits','bottle',1500,2300,1,2],['750ml Cellar Cask','Spirits','bottle',1500,2300,2,2],['250ml Just Riatt','Spirits','bottle',600,900,3,2],['250ml Kibao','Spirits','bottle',500,800,0,2],['750ml Origin','Spirits','bottle',1500,2300,1,2],['250ml Origin','Spirits','bottle',600,900,2,2],
  ['750ml Red Label','Spirits','bottle',1874,2900,5,2],['350ml Red Label','Spirits','bottle',868,1200,1,2],['250ml Red Label','Spirits','bottle',700,1100,2,2],['750ml Vat 69','Spirits','bottle',1458,2000,1,2],['350ml Vat 69','Spirits','bottle',792,1200,2,2],['750ml Black & White','Spirits','bottle',1700,1700,0,2],['350ml Black & White','Spirits','bottle',850,850,0,2],['750ml Best Whisky','Spirits','bottle',1900,3000,3,2],['250ml Best Whisky','Spirits','bottle',650,1000,2,2],['750ml Best Gin','Spirits','bottle',1800,3000,0,2],['250ml Best Gin','Spirits','bottle',650,1000,0,2],['750ml V&A','Spirits','bottle',1600,2500,0,2],['250ml V&A','Spirits','bottle',650,1000,0,2],['750ml County','Spirits','bottle',1600,2500,5,2],['250ml County','Spirits','bottle',650,1000,5,2],['750ml Hunters','Spirits','bottle',1100,1500,0,2],['350ml Hunters','Spirits','bottle',600,800,0,2],['250ml Hunters','Spirits','bottle',450,650,0,2],['750ml Crazy Cock','Spirits','bottle',1200,1700,0,2],['350ml Crazy Cock','Spirits','bottle',600,850,0,2],['250ml Crazy Cock','Spirits','bottle',450,650,0,2],['750ml Viceroy','Spirits','bottle',1280,1700,2,2],['350ml Viceroy','Spirits','bottle',684,850,14,2],['250ml Viceroy','Spirits','bottle',468,650,2,2],['750ml Richot','Spirits','bottle',1298,1700,3,2],['350ml Richot','Spirits','bottle',603,850,4,2],['250ml Richot','Spirits','bottle',436,650,0,2],['750ml Captain Morgan','Spirits','bottle',1298,1400,2,2],['250ml Captain Morgan','Spirits','bottle',345,450,12,2],
  // Cans and soft drinks from the visible sheets
  ['Manyatta','Cans','can',60,100,2,5],['Monster','Cans','can',150,250,2,5],['Pineapple Punch Can','Cans','can',80,150,2,5],['Balozi','Cans','can',180,280,0,5],['Faxe','Cans','can',180,280,0,5],['O.J.','Cans','can',100,180,1,5],['Red Bull','Cans','can',180,300,6,5],['Guarana','Cans','can',100,180,4,5],
  ['2 Ltrs Soda','Soft Drinks','bottle',130,200,14,8],['1.25 Ltrs Soda','Soft Drinks','bottle',90,150,1,8],['500ml Soda','Soft Drinks','bottle',65,100,15,8],['300ml Soda','Soft Drinks','bottle',45,80,6,8],['Mwala','Soft Drinks','bottle',50,90,5,8],['Bravia / Bravado 500ml','Soft Drinks','bottle',50,90,7,8],['Predator','Soft Drinks','can',80,130,2,8],['Afia','Soft Drinks','bottle',80,130,6,8],['Lemonade','Soft Drinks','bottle',50,90,2,8],['1ltr Delmonte','Soft Drinks','bottle',160,250,0,4],['1ltr Minute Maid','Soft Drinks','bottle',170,270,4,4],['400ml Minute Maid','Soft Drinks','bottle',100,170,7,4],['Milk','Soft Drinks','bottle',70,120,0,4],['1ltr Water','Water','bottle',50,100,0,6],['500ml Water','Water','bottle',35,70,8,10],
  // Other items visible
  ['Sport','Other','bottle',150,250,10,5],['Safari','Other','bottle',150,250,34,8],['Trust / KISS','Other','bottle',100,180,34,8],['Fresh','Other','bottle',100,180,0,8],['Njugu','Other','pack',30,70,1,5],['Mara Moja','Other','pack',40,80,5,5],['Panadol','Other','pack',100,200,34,5],['Matchbox','Other','box',30,60,3,5],['Dark Keg','Other','bottle',120,200,0,5],['750ml Smirnoff Vodka','Spirits','bottle',1298,1900,2,2],['350ml Smirnoff Vodka','Spirits','bottle',603,850,0,2],['250ml Smirnoff Vodka','Spirits','bottle',436,650,6,2],['750ml Chrome','Spirits','bottle',883,1000,1,2],['250ml Chrome','Spirits','bottle',217,300,10,2],['750ml Kane Extra','Spirits','bottle',500,600,0,2],['250ml Kane Extra','Spirits','bottle',300,400,10,2],['750ml Origin','Spirits','bottle',633,1000,0,2],['250ml Origin','Spirits','bottle',241,300,7,2],['750ml V&A','Spirits','bottle',803,1300,0,2],['250ml V&A','Spirits','bottle',310,450,0,2],['750ml County','Spirits','bottle',942,1400,0,2],['250ml County','Spirits','bottle',345,450,12,2],['750ml Konyagi','Spirits','bottle',900,1200,0,2],['250ml Konyagi','Spirits','bottle',350,450,0,2],['750ml Best Gin','Spirits','bottle',1000,1300,0,2],['250ml Best Gin','Spirits','bottle',500,650,0,2],['750ml Best Whisky','Spirits','bottle',1000,1400,0,2],['250ml Best Whisky','Spirits','bottle',550,650,0,2]
 ];
 const add=db.prepare(`INSERT INTO products(name,category_id,unit,buy_price,sell_price,stock,reorder_level,price_estimated_buy,price_estimated_sell,source_note) VALUES(?,?,?,?,?,?,?,?,?,?)`);
 const seen=new Set();
 const uniqueRows=rows.filter(r=>{const k=r[0]+'|'+r[2]; if(seen.has(k)) return false; seen.add(k); return true;});
 const move=db.prepare(`INSERT INTO stock_moves(product_id,move_type,qty,unit_cost,reference,move_date,note) VALUES(?,?,?,?,?,?,?)`);
 const hist=db.prepare(`INSERT INTO price_history(product_id,price_type,price,effective_date,estimated,source_note) VALUES(?,?,?,?,?,?)`);
 const tx=db.transaction(()=>{ for(const r of uniqueRows){const [name,cat,unit,buy,sell,stock,reorder]=r; const clearPrices=new Set(['Guinness','Guinness Smooth','Tusker Lager','Tusker Cider','Whitecap','Balozi','Tusker Lite','Black Ice','Pineapple Punch','King Fisher','K.O','Hunter Gold','Savannah','750ml Vat 69','350ml Vat 69','750ml Richot','350ml Richot','250ml Richot','750ml Bond 7','350ml Bond 7','250ml Bond 7','750ml Gilbeys','350ml Gilbeys','250ml Gilbeys','750ml Viceroy','350ml Viceroy','250ml Viceroy','750ml Hunters','350ml Hunters','250ml Hunters','750ml Crazy Cock','350ml Crazy Cock','250ml Crazy Cock','750ml Smirnoff Vodka','350ml Smirnoff Vodka','250ml Smirnoff Vodka','750ml Chrome','250ml Chrome','750ml Origin','250ml Origin','750ml V&A','250ml V&A','750ml Captain Morgan','250ml Captain Morgan','250ml County','750ml County','750ml Konyagi','250ml Konyagi','750ml Best Gin','250ml Best Gin','750ml Best Whisky','250ml Best Whisky']); const estimated=!clearPrices.has(name); const p=add.run(name,cats[cat],unit,buy,sell,stock,reorder,estimated?1:0,estimated?1:0,estimated?'Imported from photographed paper ledger; price estimated where handwriting was unclear.':'Imported from photographed paper ledger; price readable.'); if(stock) move.run(p.lastInsertRowid,'OPENING',stock,buy,'Paper ledger opening stock',today(),estimated?'Imported/estimated baseline stock':'Imported baseline stock'); hist.run(p.lastInsertRowid,'BUY',buy,today(),estimated?1:0,'Initial import from photographed paper ledger'); hist.run(p.lastInsertRowid,'SELL',sell,today(),estimated?1:0,'Initial import from photographed paper ledger'); }}); tx();
}
init();

const getLocation = id => db.prepare('SELECT * FROM locations WHERE id=? AND active=1').get(Number(id)) || db.prepare("SELECT * FROM locations WHERE name='Big Club'").get();
const stockAt = (locationId, productId) => db.prepare('SELECT quantity,reorder_level FROM location_stock WHERE location_id=? AND product_id=?').get(locationId,productId) || {quantity:0,reorder_level:null};
const ensureStock = (locationId, productId) => db.prepare('INSERT OR IGNORE INTO location_stock(location_id,product_id,quantity,reorder_level) SELECT ?,id,0,reorder_level FROM products WHERE id=?').run(locationId,productId);
const changeStock = (locationId, productId, delta) => { ensureStock(locationId,productId); const row=stockAt(locationId,productId); if(row.quantity+delta<0) throw Error(`Not enough stock. Available: ${row.quantity}`); db.prepare('UPDATE location_stock SET quantity=quantity+? WHERE location_id=? AND product_id=?').run(delta,locationId,productId); };
const locFilter = (column, locationId, params) => { if(locationId && locationId!=='all'){params.push(Number(locationId)); return ` AND ${column}=?`; } return ''; };

function auth(req,res,next){ const token=req.headers.authorization?.replace('Bearer ',''); if(!token) return res.status(401).json({error:'Login required'}); const s=db.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND u.active=1').get(token); if(!s) return res.status(401).json({error:'Session expired'}); req.user=s; next(); }
const allow=(...roles)=>(req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'Permission denied'});

app.post('/api/login',(req,res)=>{try{const {username,password}=req.body||{};const u=db.prepare('SELECT * FROM users WHERE username=? AND active=1').get(cleanText(username,60));if(!u||!password||!verifyPassword(password,u.password_hash))return res.status(401).json({error:'Invalid username or password'});if(!u.password_hash.startsWith('scrypt$'))db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(hashPassword(password),u.id);const token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions(token,user_id) VALUES(?,?)').run(token,u.id);res.json({token,user:{id:u.id,username:u.username,role:u.role}})}catch(e){res.status(400).json({error:'Could not sign in'})}});
app.get('/api/me',auth,(req,res)=>res.json({id:req.user.id,username:req.user.username,role:req.user.role}));
app.post('/api/logout',auth,(req,res)=>{db.prepare('DELETE FROM sessions WHERE user_id=?').run(req.user.id);res.json({ok:true})});
app.get('/api/users',auth,allow('Administrator/Owner'),(req,res)=>res.json(db.prepare('SELECT id,username,role,active,created_at FROM users ORDER BY username').all()));
app.post('/api/users',auth,allow('Administrator/Owner'),(req,res)=>{try{const x=req.body||{},username=cleanText(x.username,60),password=String(x.password||'');const roles=['Administrator/Owner','Manager','Cashier','Stock clerk'];if(!/^[a-zA-Z0-9._-]{3,60}$/.test(username))throw Error('Username must be 3–60 letters, numbers, dots, dashes or underscores');if(password.length<8)throw Error('Password must be at least 8 characters');if(!roles.includes(x.role))throw Error('Choose a valid role');const r=db.prepare('INSERT INTO users(username,password_hash,role) VALUES(?,?,?)').run(username,hashPassword(password),x.role);audit('CREATE','user',r.lastInsertRowid,`${username} (${x.role})`,req.user.username);res.json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/users/:id',auth,allow('Administrator/Owner'),(req,res)=>{try{const x=req.body||{},id=Number(req.params.id),u=db.prepare('SELECT * FROM users WHERE id=?').get(id);if(!u)throw Error('User not found');if(id===req.user.id&&x.active===false)throw Error('You cannot deactivate your own account');if(x.role&&!['Administrator/Owner','Manager','Cashier','Stock clerk'].includes(x.role))throw Error('Choose a valid role');if(x.password&&String(x.password).length<8)throw Error('Password must be at least 8 characters');db.prepare('UPDATE users SET role=?,active=?,password_hash=? WHERE id=?').run(x.role||u.role,x.active===false?0:1,x.password?hashPassword(x.password):u.password_hash,id);if(x.password||x.active===false)db.prepare('DELETE FROM sessions WHERE user_id=?').run(id);audit('UPDATE','user',id,`${u.username} updated`,req.user.username);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});

app.get('/api/locations',auth,(req,res)=>res.json(db.prepare('SELECT * FROM locations WHERE active=1 ORDER BY CASE name WHEN \'Big Club\' THEN 0 WHEN \'Small Club\' THEN 1 WHEN \'Store\' THEN 2 ELSE 3 END,name').all()));
app.post('/api/locations',auth,allow('Administrator/Owner','Manager'),(req,res)=>{try{const x=req.body||{},name=cleanText(x.name,80),type=['OUTLET','STORE','COUNTER'].includes(x.type)?x.type:'OUTLET';if(!name)throw Error('Location name is required');const r=db.prepare('INSERT INTO locations(name,type) VALUES(?,?)').run(name,type);audit('CREATE','location',r.lastInsertRowid,`${name} (${type})`,req.user.username);res.json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/purchases',auth,allow('Administrator/Owner','Manager','Stock clerk'),(req,res)=>{try{const x=req.body||{},loc=getLocation(x.location_id);if(!Array.isArray(x.items)||!x.items.length)throw Error('Add at least one item');const out=db.transaction(()=>{const purchase=db.prepare('INSERT INTO purchases(supplier,invoice_no,purchase_date,total,note,location_id) VALUES(?,?,?,?,?,?)').run(cleanText(x.supplier,120),cleanText(x.invoice_no,120),x.purchase_date||today(),0,cleanText(x.note,500),loc.id);let total=0;for(const i of x.items){const p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(i.product_id),q=num(i.qty),price=num(i.buy_price);if(!p||q<=0||price<0)throw Error('Invalid purchase line');total+=q*price;db.prepare('INSERT INTO purchase_items(purchase_id,product_id,qty,buy_price,line_total,estimated) VALUES(?,?,?,?,?,?)').run(purchase.lastInsertRowid,p.id,q,price,q*price,i.estimated?1:0);changeStock(loc.id,p.id,q);db.prepare('UPDATE products SET buy_price=?,price_estimated_buy=?,source_note=? WHERE id=?').run(price,i.estimated?1:0,i.estimated?'Purchase price marked estimated':'Purchase recorded',p.id);db.prepare('INSERT INTO stock_moves(product_id,location_id,move_type,qty,unit_cost,reference,note,move_date,purchase_id) VALUES(?,?,?,?,?,?,?,?,?)').run(p.id,loc.id,'IN',q,price,`Purchase #${purchase.lastInsertRowid}`,`Supplier: ${x.supplier||''}`,x.purchase_date||today(),purchase.lastInsertRowid);db.prepare('INSERT INTO price_history(product_id,price_type,price,effective_date,estimated,source_note) VALUES(?,?,?,?,?,?)').run(p.id,'BUY',price,x.purchase_date||today(),i.estimated?1:0,'Purchase record')}db.prepare('UPDATE purchases SET total=? WHERE id=?').run(total,purchase.lastInsertRowid);return{id:purchase.lastInsertRowid,total}})();audit('CREATE','purchase',out.id,`${loc.name}: Purchase ${out.total}`,req.user.username);res.json(out)}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/expenses',auth,allow('Administrator/Owner','Manager'),(req,res)=>{try{const x=req.body||{},loc=getLocation(x.location_id);if(num(x.amount)<=0)throw Error('Amount must be greater than zero');const r=db.prepare('INSERT INTO expenses(expense_date,category,amount,description,location_id) VALUES(?,?,?,?,?)').run(x.expense_date||today(),cleanText(x.category,80)||'Other',num(x.amount),cleanText(x.description,500),loc.id);audit('CREATE','expense',r.lastInsertRowid,`${loc.name}: ${x.category} ${x.amount}`,req.user.username);res.json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/closing',auth,allow('Administrator/Owner','Manager'),(req,res)=>{try{const x=req.body||{},loc=getLocation(x.location_id),d=x.close_date||today();if(!validDate(d))throw Error('Enter a valid closing date');const by=Object.fromEntries(db.prepare('SELECT payment_method,COALESCE(SUM(total),0) total FROM sales WHERE sale_date=? AND location_id=? AND voided_at IS NULL GROUP BY payment_method').all(d,loc.id).map(r=>[r.payment_method,r.total])),exp=db.prepare('SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE expense_date=? AND location_id=?').get(d,loc.id).total,expected=num(x.opening_cash)+num(by.Cash)-num(exp),actual=num(x.actual_cash),diff=actual-expected;db.prepare(`INSERT INTO location_closings(location_id,close_date,opening_cash,cash_sales,mpesa_sales,card_sales,other_sales,expenses,expected_cash,actual_cash,difference,closed_at,closed_by,note) VALUES(?,?,?,?,?,?,?,?,?,?,?,datetime('now'),?,?) ON CONFLICT(location_id,close_date) DO UPDATE SET opening_cash=excluded.opening_cash,cash_sales=excluded.cash_sales,mpesa_sales=excluded.mpesa_sales,card_sales=excluded.card_sales,other_sales=excluded.other_sales,expenses=excluded.expenses,expected_cash=excluded.expected_cash,actual_cash=excluded.actual_cash,difference=excluded.difference,closed_at=excluded.closed_at,closed_by=excluded.closed_by,note=excluded.note`).run(loc.id,d,num(x.opening_cash),by.Cash||0,by['M-Pesa']||0,by.Card||0,by.Other||0,exp,expected,actual,diff,req.user.username,cleanText(x.note,500));audit('CLOSE','daily_closing',loc.id,`${loc.name} ${d}: difference ${diff}`,req.user.username);res.json({date:d,expected_cash:expected,actual_cash:actual,difference:diff})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/closing',auth,(req,res)=>{const d=req.query.date||today(),loc=getLocation(req.query.location_id),closed=db.prepare('SELECT * FROM location_closings WHERE close_date=? AND location_id=?').get(d,loc.id),opening=closed?.opening_cash||0,by=Object.fromEntries(db.prepare('SELECT payment_method,COALESCE(SUM(total),0) total FROM sales WHERE sale_date=? AND location_id=? AND voided_at IS NULL GROUP BY payment_method').all(d,loc.id).map(r=>[r.payment_method,r.total])),exp=db.prepare('SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE expense_date=? AND location_id=?').get(d,loc.id).total;res.json({date:d,opening_cash:opening,cash_sales:by.Cash||0,mpesa_sales:by['M-Pesa']||0,card_sales:by.Card||0,other_sales:by.Other||0,expenses:exp,expected_cash:num(opening)+num(by.Cash)-num(exp),closing:closed||null})});
app.get('/api/reports',auth,(req,res)=>{const from=req.query.from||today(),to=req.query.to||today(),loc=req.query.location_id&&req.query.location_id!=='all'?getLocation(req.query.location_id):null,lf=loc?' AND location_id=?':'',args=loc?[from,to,loc.id]:[from,to],sales=db.prepare(`SELECT COALESCE(SUM(total),0) total,COUNT(*) count FROM sales WHERE sale_date BETWEEN ? AND ? AND voided_at IS NULL${lf}`).get(...args),expenses=db.prepare(`SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE expense_date BETWEEN ? AND ?${lf}`).get(...args),products=loc?db.prepare(`SELECT p.id,p.name,p.unit,COALESCE(ls.quantity,0) stock,p.buy_price,p.sell_price,p.price_estimated_buy,p.price_estimated_sell,COALESCE(SUM(CASE WHEN sm.move_type='SALE' AND sm.move_date BETWEEN ? AND ? THEN sm.qty ELSE 0 END),0) sold,COALESCE(SUM(CASE WHEN sm.move_type IN ('IN','OPENING','TRANSFER_IN') AND sm.move_date BETWEEN ? AND ? THEN sm.qty ELSE 0 END),0) received FROM products p LEFT JOIN location_stock ls ON ls.product_id=p.id AND ls.location_id=? LEFT JOIN stock_moves sm ON sm.product_id=p.id AND sm.location_id=? WHERE p.active=1 GROUP BY p.id ORDER BY sold DESC`).all(from,to,from,to,loc.id,loc.id):db.prepare(`SELECT p.id,p.name,p.unit,COALESCE(SUM(ls.quantity),0) stock,p.buy_price,p.sell_price,p.price_estimated_buy,p.price_estimated_sell,0 sold,0 received FROM products p LEFT JOIN location_stock ls ON ls.product_id=p.id WHERE p.active=1 GROUP BY p.id`).all(),byDay=db.prepare(`SELECT sale_date date,ROUND(SUM(total),2) sales FROM sales WHERE sale_date BETWEEN ? AND ? AND voided_at IS NULL${lf} GROUP BY sale_date ORDER BY sale_date`).all(...args),byPay=db.prepare(`SELECT payment_method,ROUND(SUM(total),2) total FROM sales WHERE sale_date BETWEEN ? AND ? AND voided_at IS NULL${lf} GROUP BY payment_method`).all(...args),byExpense=db.prepare(`SELECT category,ROUND(SUM(amount),2) total FROM expenses WHERE expense_date BETWEEN ? AND ?${lf} GROUP BY category ORDER BY total DESC`).all(...args);res.json({from,to,location:loc?.name||'All Locations',sales,expenses,cogs:0,gross_profit:sales.total,profit:sales.total-expenses.total,products,byDay,byPay,byExpense})});
app.get('/api/dashboard',auth,(req,res)=>{
 const d=req.query.date||today();
 const locationId=req.query.location_id, args=[d],sf=locFilter('location_id',locationId,args),sales=db.prepare(`SELECT COALESCE(SUM(total),0) total,COUNT(*) count FROM sales WHERE sale_date=? AND voided_at IS NULL${sf}`).get(...args);
 const ea=[d],ef=locFilter('location_id',locationId,ea),exp=db.prepare(`SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE expense_date=?${ef}`).get(...ea);
 const stock=locationId&&locationId!=='all'?db.prepare(`SELECT COALESCE(SUM(ls.quantity*p.buy_price),0) value,COUNT(p.id) products,SUM(CASE WHEN ls.quantity<=COALESCE(ls.reorder_level,p.reorder_level) THEN 1 ELSE 0 END) low FROM products p LEFT JOIN location_stock ls ON ls.product_id=p.id AND ls.location_id=? WHERE p.active=1`).get(locationId):db.prepare('SELECT COALESCE(SUM(quantity*p.buy_price),0) value,COUNT(DISTINCT product_id) products,SUM(CASE WHEN quantity<=COALESCE(reorder_level,0) THEN 1 ELSE 0 END) low FROM location_stock JOIN products p ON p.id=product_id WHERE p.active=1').get();
 const ta=[d],tf=locFilter('s.location_id',locationId,ta),top=db.prepare(`SELECT p.name,SUM(si.qty) qty,SUM(si.line_total) revenue FROM sale_items si JOIN sales s ON s.id=si.sale_id JOIN products p ON p.id=si.product_id WHERE s.sale_date=? AND s.voided_at IS NULL${tf} GROUP BY p.id ORDER BY revenue DESC LIMIT 5`).all(...ta);
 const trend=db.prepare(`WITH RECURSIVE days(d) AS (SELECT date(?) UNION ALL SELECT date(d,'-1 day') FROM days WHERE d>date(?,'-6 day')) SELECT d date,COALESCE((SELECT SUM(total) FROM sales WHERE sale_date=d AND voided_at IS NULL${locationId&&locationId!=='all'?' AND location_id='+Number(locationId):''}),0) sales FROM days ORDER BY d`).all(d,d);
 const closing=locationId&&locationId!=='all'?db.prepare('SELECT * FROM location_closings WHERE close_date=? AND location_id=?').get(d,locationId):null;
 res.json({date:d,sales,expenses:exp,profit:sales.total-exp.total,stock,top,trend,closing});
});

app.get('/api/products',auth,(req,res)=>{const l=req.query.location_id;if(l&&l!=='all')return res.json(db.prepare(`SELECT p.*,c.name category,COALESCE(ls.quantity,0) stock,COALESCE(ls.reorder_level,p.reorder_level) reorder_level FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN location_stock ls ON ls.product_id=p.id AND ls.location_id=? WHERE p.active=1 ORDER BY c.name,p.name`).all(l));res.json(db.prepare(`SELECT p.*,c.name category,COALESCE(SUM(ls.quantity),0) stock FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN location_stock ls ON ls.product_id=p.id WHERE p.active=1 GROUP BY p.id ORDER BY c.name,p.name`).all())});
app.get('/api/products/:id/insights',auth,(req,res)=>{const id=req.params.id;const p=db.prepare(`SELECT p.*,c.name category FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.id=?`).get(id);if(!p)return res.status(404).json({error:'Product not found'});const sold=db.prepare(`SELECT COALESCE(SUM(si.qty),0) qty,COALESCE(SUM(si.line_total),0) revenue FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE si.product_id=? AND s.sale_date>=date(?,'-6 day') AND s.sale_date<=?`).get(id,today(),today());const prev=db.prepare(`SELECT COALESCE(SUM(si.qty),0) qty FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE si.product_id=? AND s.sale_date>=date(?,'-13 day') AND s.sale_date<=date(?,'-7 day')`).get(id,today(),today());const trendPct=prev.qty?((sold.qty-prev.qty)/prev.qty*100):null;const hist=db.prepare('SELECT * FROM price_history WHERE product_id=? ORDER BY effective_date DESC,id DESC').all(id);const daily=db.prepare(`WITH RECURSIVE days(d) AS (SELECT date(?) UNION ALL SELECT date(d,'-1 day') FROM days WHERE d>date(?,'-6 day')) SELECT d date,COALESCE((SELECT SUM(si.qty) FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE si.product_id=? AND s.sale_date=d),0) qty FROM days ORDER BY d`).all(today(),today(),id);res.json({product:p,sold,previous_qty:prev.qty,trend_pct:trendPct,margin:p.sell_price-p.buy_price,margin_pct:p.sell_price?((p.sell_price-p.buy_price)/p.sell_price*100):0,history:hist,daily,reorder:p.stock<=p.reorder_level});});
app.post('/api/products',auth,allow('Administrator/Owner','Manager'),(req,res)=>{try{const x=req.body;if(!x.name)throw Error('Product name is required');const estimated=!!x.price_estimated;const r=db.prepare(`INSERT INTO products(name,category_id,unit,buy_price,sell_price,stock,reorder_level,price_estimated_buy,price_estimated_sell,source_note) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(x.name,x.category_id||null,x.unit||'pcs',num(x.buy_price),num(x.sell_price),num(x.stock),num(x.reorder_level),estimated?1:0,estimated?1:0,x.source_note||'');if(num(x.stock))db.prepare(`INSERT INTO stock_moves(product_id,move_type,qty,unit_cost,reference,move_date,note) VALUES(?,?,?,?,?,?,?)`).run(r.lastInsertRowid,'OPENING',num(x.stock),num(x.buy_price),'Opening stock',today(),'Manual opening stock');audit('CREATE','product',r.lastInsertRowid,x.name,req.user.username);res.json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/products/:id',auth,allow('Administrator/Owner','Manager'),(req,res)=>{try{const x=req.body;const old=db.prepare('SELECT * FROM products WHERE id=?').get(req.params.id);db.prepare(`UPDATE products SET name=?,category_id=?,unit=?,buy_price=?,sell_price=?,reorder_level=?,price_estimated_buy=?,price_estimated_sell=?,source_note=? WHERE id=?`).run(x.name,x.category_id||null,x.unit||'pcs',num(x.buy_price),num(x.sell_price),num(x.reorder_level),x.price_estimated_buy?1:0,x.price_estimated_sell?1:0,x.source_note||'',req.params.id);if(old&&old.buy_price!==num(x.buy_price))db.prepare(`INSERT INTO price_history(product_id,price_type,price,effective_date,estimated,source_note) VALUES(?,?,?,?,?,?)`).run(req.params.id,'BUY',num(x.buy_price),today(),x.price_estimated_buy?1:0,'Product price update');if(old&&old.sell_price!==num(x.sell_price))db.prepare(`INSERT INTO price_history(product_id,price_type,price,effective_date,estimated,source_note) VALUES(?,?,?,?,?,?)`).run(req.params.id,'SELL',num(x.sell_price),today(),x.price_estimated_sell?1:0,'Product price update');audit('UPDATE','product',req.params.id,x.name,req.user.username);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/products/:id',auth,allow('Administrator/Owner','Manager'),(req,res)=>{db.prepare('UPDATE products SET active=0 WHERE id=?').run(req.params.id);audit('ARCHIVE','product',req.params.id,'',req.user.username);res.json({ok:true})});
app.get('/api/categories',auth,(req,res)=>res.json(db.prepare('SELECT * FROM categories ORDER BY name').all()));

app.post('/api/stock',auth,allow('Administrator/Owner','Manager','Stock clerk'),(req,res)=>{try{const x=req.body||{},qty=num(x.qty),type=String(x.move_type||''),loc=getLocation(x.location_id);if(!['IN','OUT','ADJUSTMENT_IN','ADJUSTMENT_OUT'].includes(type)||qty<=0)throw Error('Enter a valid positive stock movement');if(type.startsWith('ADJUSTMENT')&&!cleanText(x.reason,120))throw Error('A reason is required for stock corrections');const p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(x.product_id);if(!p)throw Error('Product not found');const delta=['OUT','ADJUSTMENT_OUT'].includes(type)?-qty:qty;const note=[cleanText(x.reason,120),cleanText(x.note,400)].filter(Boolean).join(' — ');db.transaction(()=>{changeStock(loc.id,p.id,delta);db.prepare('INSERT INTO stock_moves(product_id,location_id,move_type,qty,unit_cost,reference,note,move_date) VALUES(?,?,?,?,?,?,?,?)').run(p.id,loc.id,type,qty,num(x.unit_cost||p.buy_price),cleanText(x.reference,120),note,x.move_date||today())})();audit('STOCK_'+type,'stock',p.id,`${loc.name}: ${p.name} qty ${qty}; ${note}`,req.user.username);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/stock/count',auth,allow('Administrator/Owner','Manager','Stock clerk'),(req,res)=>{try{const x=req.body||{},loc=getLocation(x.location_id),p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(x.product_id),counted=num(x.quantity),reason=cleanText(x.reason,160);if(!p||counted<0)throw Error('Enter a valid product and counted quantity');if(!reason)throw Error('A reason is required when setting stock');const current=stockAt(loc.id,p.id).quantity,delta=counted-current,type=delta>=0?'ADJUSTMENT_IN':'ADJUSTMENT_OUT';db.transaction(()=>{changeStock(loc.id,p.id,delta);db.prepare('INSERT INTO stock_moves(product_id,location_id,move_type,qty,unit_cost,reference,note,move_date) VALUES(?,?,?,?,?,?,?,?)').run(p.id,loc.id,type,Math.abs(delta),p.buy_price,'Physical count',reason,x.move_date||today())})();audit('SET_STOCK','stock',p.id,`${loc.name}: ${p.name} ${current} → ${counted}; ${reason}`,req.user.username);res.json({ok:true,previous:current,quantity:counted})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/stock/moves',auth,(req,res)=>res.json(db.prepare(`SELECT m.*,p.name product,p.unit FROM stock_moves m JOIN products p ON p.id=m.product_id ORDER BY m.move_date DESC,m.id DESC LIMIT 300`).all()));

app.post('/api/sales',auth,allow('Administrator/Owner','Manager','Cashier'),(req,res)=>{try{const x=req.body||{},loc=getLocation(x.location_id);if(!Array.isArray(x.items)||!x.items.length)throw Error('Add at least one item');const out=db.transaction(()=>{let total=0,checked=[];for(const i of x.items){const p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(i.product_id),q=num(i.qty),available=stockAt(loc.id,i.product_id).quantity;if(!p||q<=0)throw Error('Invalid sale item');if(available<q)throw Error(`Not enough ${p.name}. Available: ${available}`);const price=num(i.unit_price||p.sell_price);total+=q*price;checked.push({p,q,price})}const s=db.prepare('INSERT INTO sales(sale_date,total,payment_method,note,location_id) VALUES(?,?,?,?,?)').run(x.sale_date||today(),total,x.payment_method||'Cash',x.note||'',loc.id);for(const z of checked){db.prepare('INSERT INTO sale_items(sale_id,product_id,qty,unit_price,line_total) VALUES(?,?,?,?,?)').run(s.lastInsertRowid,z.p.id,z.q,z.price,z.q*z.price);changeStock(loc.id,z.p.id,-z.q);db.prepare('INSERT INTO stock_moves(product_id,location_id,move_type,qty,unit_cost,reference,move_date,note) VALUES(?,?,?,?,?,?,?,?)').run(z.p.id,loc.id,'SALE',z.q,z.p.buy_price,`Sale #${s.lastInsertRowid}`,x.sale_date||today(),'Automatic stock deduction')}return{id:s.lastInsertRowid,total}})();audit('CREATE','sale',out.id,`${loc.name}: Sale ${out.total}`,req.user.username);res.json(out)}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/sales',auth,(req,res)=>{const from=req.query.from||today(),to=req.query.to||today();res.json(db.prepare(`SELECT s.*,GROUP_CONCAT(p.name||' x'||si.qty, ', ') items FROM sales s LEFT JOIN sale_items si ON si.sale_id=s.id LEFT JOIN products p ON p.id=si.product_id WHERE s.sale_date BETWEEN ? AND ? GROUP BY s.id ORDER BY s.sale_date DESC,s.id DESC`).all(from,to))});
app.post('/api/sales/:id/void',auth,allow('Administrator/Owner','Manager'),(req,res)=>{try{const id=Number(req.params.id),reason=cleanText(req.body?.reason,250),sale=db.prepare('SELECT * FROM sales WHERE id=?').get(id);if(!reason||!sale||sale.voided_at)throw Error(!reason?'A void reason is required':'Sale cannot be voided');db.transaction(()=>{for(const item of db.prepare('SELECT si.*,p.buy_price FROM sale_items si JOIN products p ON p.id=si.product_id WHERE si.sale_id=?').all(id)){changeStock(sale.location_id,item.product_id,item.qty);db.prepare('INSERT INTO stock_moves(product_id,location_id,move_type,qty,unit_cost,reference,note,move_date) VALUES(?,?,?,?,?,?,?,?)').run(item.product_id,sale.location_id,'VOID',item.qty,item.buy_price,`Void sale #${id}`,reason,today())}db.prepare("UPDATE sales SET voided_at=datetime('now'),voided_by=?,void_reason=? WHERE id=?").run(req.user.username,reason,id)})();audit('VOID','sale',id,reason,req.user.username);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});

app.post('/api/expenses',auth,allow('Administrator/Owner','Manager'),(req,res)=>{try{const x=req.body;if(num(x.amount)<=0)throw Error('Amount must be greater than zero');const r=db.prepare('INSERT INTO expenses(expense_date,category,amount,description) VALUES(?,?,?,?)').run(x.expense_date||today(),x.category||'Other',num(x.amount),x.description||'');audit('CREATE','expense',r.lastInsertRowid,`${x.category} ${x.amount}`,req.user.username);res.json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/expenses',auth,(req,res)=>{const from=req.query.from||today(),to=req.query.to||today();res.json(db.prepare('SELECT * FROM expenses WHERE expense_date BETWEEN ? AND ? ORDER BY expense_date DESC,id DESC').all(from,to))});

app.post('/api/purchases',auth,allow('Administrator/Owner','Manager','Stock clerk'),(req,res)=>{try{const x=req.body;if(!Array.isArray(x.items)||!x.items.length)throw Error('Add at least one item');const tx=db.transaction(()=>{let total=0;const p=db.prepare('INSERT INTO purchases(supplier,invoice_no,purchase_date,total,note) VALUES(?,?,?,?,?)');const purchase=p.run(x.supplier||'',x.invoice_no||'',x.purchase_date||today(),0,x.note||'');const item=db.prepare('INSERT INTO purchase_items(purchase_id,product_id,qty,buy_price,line_total,estimated) VALUES(?,?,?,?,?,?)');const move=db.prepare(`INSERT INTO stock_moves(product_id,move_type,qty,unit_cost,reference,note,move_date,purchase_id) VALUES(?,?,?,?,?,?,?,?)`);for(const i of x.items){const product=db.prepare('SELECT * FROM products WHERE id=?').get(i.product_id);if(!product)throw Error('Invalid product');const q=num(i.qty),price=num(i.buy_price);if(q<=0||price<0)throw Error('Invalid purchase line');total+=q*price;item.run(purchase.lastInsertRowid,product.id,q,price,q*price,i.estimated?1:0);db.prepare('UPDATE products SET stock=stock+?,buy_price=?,price_estimated_buy=?,source_note=? WHERE id=?').run(q,price,i.estimated?1:0,i.estimated?'Purchase price marked estimated':'Purchase recorded',product.id);move.run(product.id,'IN',q,price,`Purchase #${purchase.lastInsertRowid}`,`Supplier: ${x.supplier||''}`,x.purchase_date||today(),purchase.lastInsertRowid);db.prepare(`INSERT INTO price_history(product_id,price_type,price,effective_date,estimated,source_note) VALUES(?,?,?,?,?,?)`).run(product.id,'BUY',price,x.purchase_date||today(),i.estimated?1:0,'Purchase record')}db.prepare('UPDATE purchases SET total=? WHERE id=?').run(total,purchase.lastInsertRowid);return{id:purchase.lastInsertRowid,total}});const out=tx();audit('CREATE','purchase',out.id,`Purchase ${out.total}`,req.user.username);res.json(out)}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/purchases',auth,(req,res)=>res.json(db.prepare(`SELECT p.*,COALESCE(GROUP_CONCAT(pr.name||' x'||pi.qty,'; '),'') items FROM purchases p LEFT JOIN purchase_items pi ON pi.purchase_id=p.id LEFT JOIN products pr ON pr.id=pi.product_id GROUP BY p.id ORDER BY p.purchase_date DESC,p.id DESC LIMIT 300`).all()));

app.post('/api/transfers',auth,allow('Administrator/Owner','Manager','Stock clerk'),(req,res)=>{try{const x=req.body||{},from=getLocation(x.from_location_id),to=getLocation(x.to_location_id),items=x.items;if(from.id===to.id)throw Error('Choose different source and destination');if(!Array.isArray(items)||!items.length)throw Error('Add at least one transfer item');const out=db.transaction(()=>{const t=db.prepare('INSERT INTO stock_transfers(from_location_id,to_location_id,transfer_date,created_by,note) VALUES(?,?,?,?,?)').run(from.id,to.id,x.transfer_date||today(),req.user.username,cleanText(x.note,500));for(const i of items){const q=num(i.quantity),p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(i.product_id);if(!p||q<=0)throw Error('Invalid transfer item');if(stockAt(from.id,p.id).quantity<q)throw Error(`Not enough ${p.name} in ${from.name}`);changeStock(from.id,p.id,-q);changeStock(to.id,p.id,q);db.prepare('INSERT INTO stock_transfer_items(transfer_id,product_id,quantity) VALUES(?,?,?)').run(t.lastInsertRowid,p.id,q);const move=db.prepare('INSERT INTO stock_moves(product_id,location_id,move_type,qty,unit_cost,reference,note,move_date) VALUES(?,?,?,?,?,?,?,?)');move.run(p.id,from.id,'TRANSFER_OUT',q,p.buy_price,`Transfer #${t.lastInsertRowid}`,`To ${to.name}`,x.transfer_date||today());move.run(p.id,to.id,'TRANSFER_IN',q,p.buy_price,`Transfer #${t.lastInsertRowid}`,`From ${from.name}`,x.transfer_date||today())}return {id:t.lastInsertRowid}})();audit('TRANSFER','stock_transfer',out.id,`${from.name} → ${to.name}`,req.user.username);res.json(out)}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/transfers',auth,(req,res)=>res.json(db.prepare(`SELECT t.*,f.name from_location,d.name to_location,GROUP_CONCAT(p.name||' x'||i.quantity,'; ') items FROM stock_transfers t JOIN locations f ON f.id=t.from_location_id JOIN locations d ON d.id=t.to_location_id LEFT JOIN stock_transfer_items i ON i.transfer_id=t.id LEFT JOIN products p ON p.id=i.product_id GROUP BY t.id ORDER BY t.transfer_date DESC,t.id DESC LIMIT 300`).all()));

app.get('/api/accommodation/dashboard',auth,(req,res)=>{const d=today(),rooms=db.prepare("SELECT SUM(status='Occupied') occupied,SUM(status='Available') available FROM rooms WHERE active=1").get(),checkins=db.prepare('SELECT COUNT(*) n FROM bookings WHERE check_in=?').get(d).n,checkouts=db.prepare('SELECT COUNT(*) n FROM bookings WHERE check_out=?').get(d).n,revenue=db.prepare('SELECT COALESCE(SUM(amount),0) total FROM accommodation_payments WHERE payment_date=?').get(d).total,outstanding=db.prepare(`SELECT COALESCE(SUM(b.total-COALESCE(p.paid,0)),0) total FROM bookings b LEFT JOIN (SELECT booking_id,SUM(amount) paid FROM accommodation_payments GROUP BY booking_id) p ON p.booking_id=b.id WHERE b.status NOT IN ('Cancelled')`).get().total;res.json({rooms,checkins,checkouts,revenue,outstanding})});
app.get('/api/rooms',auth,(req,res)=>res.json(db.prepare('SELECT * FROM rooms WHERE active=1 ORDER BY room_name').all()));
app.post('/api/rooms',auth,allow('Administrator/Owner','Manager'),(req,res)=>{try{const x=req.body||{};if(!cleanText(x.room_name,60))throw Error('Room name is required');const r=db.prepare('INSERT INTO rooms(room_name,room_type,price_per_night,status) VALUES(?,?,?,?)').run(cleanText(x.room_name,60),cleanText(x.room_type,60),num(x.price_per_night),x.status||'Available');audit('CREATE','room',r.lastInsertRowid,x.room_name,req.user.username);res.json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/bookings',auth,(req,res)=>res.json(db.prepare('SELECT b.*,g.name guest,g.phone,r.room_name FROM bookings b JOIN guests g ON g.id=b.guest_id JOIN rooms r ON r.id=b.room_id ORDER BY b.check_in DESC,b.id DESC').all()));
app.post('/api/bookings',auth,allow('Administrator/Owner','Manager'),(req,res)=>{try{const x=req.body||{},checkIn=x.check_in,checkOut=x.check_out;if(!cleanText(x.guest_name,100)||!validDate(checkIn)||!validDate(checkOut)||checkOut<=checkIn)throw Error('Guest, valid check-in and later check-out are required');const room=db.prepare('SELECT * FROM rooms WHERE id=? AND active=1').get(x.room_id);if(!room)throw Error('Room not found');const clash=db.prepare("SELECT 1 FROM bookings WHERE room_id=? AND status NOT IN ('Cancelled','Checked out') AND check_in<? AND check_out>?").get(room.id,checkOut,checkIn);if(clash)throw Error('Room is already booked for these dates');const nights=Math.max(1,Math.round((Date.parse(checkOut)-Date.parse(checkIn))/86400000)),rate=num(x.rate||room.price_per_night),out=db.transaction(()=>{const g=db.prepare('INSERT INTO guests(name,phone,notes) VALUES(?,?,?)').run(cleanText(x.guest_name,100),cleanText(x.phone,50),cleanText(x.guest_notes,500));return db.prepare('INSERT INTO bookings(guest_id,room_id,check_in,check_out,nights,rate,total,status,payment_status,payment_method,note) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(g.lastInsertRowid,room.id,checkIn,checkOut,nights,rate,nights*rate,x.status||'Reserved',x.payment_status||'Unpaid',x.payment_method||'',cleanText(x.note,500))})();audit('CREATE','booking',out.lastInsertRowid,`${x.guest_name}, ${room.room_name}`,req.user.username);res.json({id:out.lastInsertRowid,total:nights*rate})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/accommodation/payments',auth,allow('Administrator/Owner','Manager','Cashier'),(req,res)=>{try{const x=req.body||{};if(num(x.amount)<=0||!x.booking_id)throw Error('Booking and positive amount are required');const r=db.prepare('INSERT INTO accommodation_payments(booking_id,amount,payment_date,payment_method,reference,received_by) VALUES(?,?,?,?,?,?)').run(x.booking_id,num(x.amount),x.payment_date||today(),x.payment_method||'Cash',cleanText(x.reference,120),req.user.username);db.prepare("UPDATE bookings SET payment_status=CASE WHEN total<=(SELECT COALESCE(SUM(amount),0) FROM accommodation_payments WHERE booking_id=?) THEN 'Paid' ELSE 'Part paid' END WHERE id=?").run(x.booking_id,x.booking_id);audit('CREATE','accommodation_payment',r.lastInsertRowid,`Booking ${x.booking_id}: ${x.amount}`,req.user.username);res.json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:e.message})}});

app.get('/api/reports',auth,(req,res)=>{const from=req.query.from||today(),to=req.query.to||today();const sales=db.prepare('SELECT COALESCE(SUM(total),0) total,COUNT(*) count FROM sales WHERE sale_date BETWEEN ? AND ? AND voided_at IS NULL').get(from,to);const expenses=db.prepare('SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE expense_date BETWEEN ? AND ?').get(from,to);const cogs=db.prepare(`SELECT COALESCE(SUM(si.qty*sm.unit_cost),0) cost FROM sale_items si JOIN sales s ON s.id=si.sale_id JOIN stock_moves sm ON sm.reference='Sale #'||s.id AND sm.product_id=si.product_id AND sm.move_type='SALE' WHERE s.sale_date BETWEEN ? AND ? AND s.voided_at IS NULL`).get(from,to);const products=db.prepare(`SELECT p.id,p.name,p.unit,p.stock,p.buy_price,p.sell_price,p.price_estimated_buy,p.price_estimated_sell,COALESCE(SUM(CASE WHEN sm.move_type='SALE' AND sm.move_date BETWEEN ? AND ? THEN sm.qty ELSE 0 END),0) sold,COALESCE(SUM(CASE WHEN sm.move_type IN ('IN','OPENING') AND sm.move_date BETWEEN ? AND ? THEN sm.qty ELSE 0 END),0) received FROM products p LEFT JOIN stock_moves sm ON sm.product_id=p.id WHERE p.active=1 GROUP BY p.id ORDER BY sold DESC`).all(from,to,from,to);const byDay=db.prepare(`SELECT sale_date date,ROUND(SUM(total),2) sales FROM sales WHERE sale_date BETWEEN ? AND ? AND voided_at IS NULL GROUP BY sale_date ORDER BY sale_date`).all(from,to);const byPay=db.prepare('SELECT payment_method,ROUND(SUM(total),2) total FROM sales WHERE sale_date BETWEEN ? AND ? AND voided_at IS NULL GROUP BY payment_method').all(from,to);const byExpense=db.prepare('SELECT category,ROUND(SUM(amount),2) total FROM expenses WHERE expense_date BETWEEN ? AND ? GROUP BY category ORDER BY total DESC').all(from,to);res.json({from,to,sales,expenses,cogs:cogs.cost,gross_profit:sales.total-cogs.cost,profit:sales.total-expenses.total-cogs.cost,products,byDay,byPay,byExpense})});

app.get('/api/price-history',auth,(req,res)=>res.json(db.prepare(`SELECT h.*,p.name product FROM price_history h JOIN products p ON p.id=h.product_id WHERE h.product_id=? ORDER BY h.effective_date DESC,h.id DESC`).all(req.query.product_id)));
app.post('/api/price-history',auth,allow('Administrator/Owner','Manager'),(req,res)=>{const x=req.body;db.prepare(`INSERT INTO price_history(product_id,price_type,price,effective_date,estimated,source_note) VALUES(?,?,?,?,?,?)`).run(x.product_id,x.price_type,x.price,x.effective_date||today(),x.estimated?1:0,x.source_note||'');res.json({ok:true})});

app.get('/api/closing',auth,(req,res)=>{const d=req.query.date||today();const opening=db.prepare('SELECT opening_cash FROM daily_closings WHERE close_date=?').get(d)?.opening_cash||0;const sales=db.prepare(`SELECT payment_method,COALESCE(SUM(total),0) total FROM sales WHERE sale_date=? AND voided_at IS NULL GROUP BY payment_method`).all(d);const by=Object.fromEntries(sales.map(x=>[x.payment_method,x.total]));const exp=db.prepare('SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE expense_date=?').get(d).total;const expected=num(opening)+num(by.Cash)-num(exp);const closed=db.prepare('SELECT * FROM daily_closings WHERE close_date=?').get(d);res.json({date:d,opening_cash:opening,cash_sales:by.Cash||0,mpesa_sales:by['M-Pesa']||0,card_sales:by.Card||0,other_sales:by.Other||0,expenses:exp,expected_cash:expected,closing:closed||null})});
app.post('/api/closing',auth,allow('Administrator/Owner','Manager'),(req,res)=>{try{const x=req.body||{},d=x.close_date||today();if(!validDate(d))throw Error('Enter a valid closing date');const sales=db.prepare(`SELECT payment_method,COALESCE(SUM(total),0) total FROM sales WHERE sale_date=? AND voided_at IS NULL GROUP BY payment_method`).all(d);const by=Object.fromEntries(sales.map(y=>[y.payment_method,y.total]));const exp=db.prepare('SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE expense_date=?').get(d).total;const expected=num(x.opening_cash)+num(by.Cash)-num(exp);const actual=num(x.actual_cash);const diff=actual-expected;db.prepare(`INSERT INTO daily_closings(close_date,opening_cash,cash_sales,mpesa_sales,card_sales,other_sales,expenses,expected_cash,actual_cash,difference,closed_at,closed_by,note) VALUES(?,?,?,?,?,?,?,?,?,?,datetime('now'),?,?) ON CONFLICT(close_date) DO UPDATE SET opening_cash=excluded.opening_cash,cash_sales=excluded.cash_sales,mpesa_sales=excluded.mpesa_sales,card_sales=excluded.card_sales,other_sales=excluded.other_sales,expenses=excluded.expenses,expected_cash=excluded.expected_cash,actual_cash=excluded.actual_cash,difference=excluded.difference,closed_at=excluded.closed_at,closed_by=excluded.closed_by,note=excluded.note`).run(d,num(x.opening_cash),by.Cash||0,by['M-Pesa']||0,by.Card||0,by.Other||0,exp,expected,actual,diff,req.user.username,cleanText(x.note,500));audit('CLOSE','daily_closing',null,`${d} difference ${diff}`,req.user.username);res.json({date:d,expected_cash:expected,actual_cash:actual,difference:diff})}catch(e){res.status(400).json({error:e.message})}});

app.get('/api/audit',auth,allow('Administrator/Owner','Manager'),(req,res)=>res.json(db.prepare('SELECT * FROM audit_log ORDER BY id DESC LIMIT 300').all()));
app.get('/api/backup',auth,allow('Administrator/Owner'),(req,res)=>{const out=path.join(path.dirname(dbPath),`club-backup-${Date.now()}.db`);db.pragma('wal_checkpoint(TRUNCATE)');fs.copyFileSync(dbPath,out);res.download(out,'park-bar-backup.db',()=>{try{fs.unlinkSync(out)}catch{}})});
app.get('/api/settings',auth,(req,res)=>res.json(Object.fromEntries(db.prepare('SELECT key,value FROM settings').all().map(x=>[x.key,x.value]))));
app.use((req,res,next)=>{if(req.path.startsWith('/api/')) return res.status(404).json({error:'Not found'});next()});
function startServer(port) {
 const server=app.listen(port,()=>console.log(`Park Bar Club Manager running at http://localhost:${port}`));
 server.once('error',(error)=>{
  if(error.code==='EADDRINUSE'&&!process.env.PORT&&port<3010){
   console.warn(`Port ${port} is already in use; trying port ${port+1}.`);
   startServer(port+1);
   return;
  }
  throw error;
 });
}
if (require.main === module) startServer(PORT);

// Vercel's Node runtime invokes this Express application as a serverless
// function. Do not open a listener when the module is loaded by Vercel.
module.exports = app;
